### ISSUE TITLE
iso24229.org not registered

### ISSUE THREAD

**Issue by douglm** [iso24229/iso24229.github.io#2]
Clicking on the links in the readme either get a bad certificate for https or unregistered domain for http

**Comment by ribose-jeffreylau** [comment]
I've updated the link in the README.  Please check if it still breaks?  Thanks!

**Comment by ronaldtse** [comment]
I have updated the DNS records so that www.iso24229.org points to iso24229.github.io. Thanks!

**Comment by ronaldtse** [comment]
<img width="948" alt="Screenshot 2023-09-28 at 1 41 02 PM" src="https://github.com/iso24229/iso24229.github.io/assets/11865/2811f0e6-d923-411c-ab20-0e945032b2a7">
